// The AI-Powered Pupil Services Leader — 30 workflows
// Size bands: xs(<500), sm(<1000), md(<3000), lg(<8000), xl(15000+)
// Locale: rural, suburban, urban (all three = universal)
// Domains: cse, plan504, compliance, mtss, related, equity, staff, budget
// Featured: 4 (IEP compliance review, annual packet synthesis, OOD placement analysis, due process prep)

const WORKFLOWS = [
  // ───────── CSE / CPSE CHAIR ─────────
  {
    id: 1,
    featured: true,
    tool: "claude",
    toolLabel: "Claude",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "IEP Draft Compliance Review",
    description: "Run a draft IEP against the clauses that actually fail on state audit — present levels, measurable goals, LRE justification, service minutes.",
    why: "Most IEPs that get flagged by SED aren't wrong on the big things — they fail on present levels that don't connect to goals, goals that aren't measurable, or LRE boilerplate that doesn't match the program. Catch it before it's signed.",
    setup: "Paste the full draft IEP. Remove student name and ID. Tell Claude the state (NY) and whether this is an initial, annual review, or reevaluation.",
    prompt: "You are a special education compliance specialist with deep knowledge of NYSED Part 200 regulations and IDEA. Audit the draft IEP below. Produce: (1) the five most likely state audit findings, ranked by severity, each citing the specific regulation (e.g., 8 NYCRR §200.4(d)(2)(iii)); (2) present levels of performance — identify any domain where the data does not support the goals written; (3) every annual goal — flag any that are not measurable, not observable, or not connected to a need named in present levels, and rewrite each flagged goal in compliant form; (4) LRE justification — is it specific to this student or boilerplate; (5) service delivery — do the frequency, duration, and location match the identified needs; (6) the one thing that would most likely cause a parent to request mediation or a due process hearing. Tone: protective of the student, protective of the district. DRAFT IEP: [paste]"
  },
  {
    id: 2,
    tool: "claude",
    toolLabel: "Claude",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Measurable Goal Writing Coach",
    description: "Turn a teacher's narrative concern into three measurable IEP goal options — behavior, condition, criterion, timeframe.",
    why: "Every CSE chair has the same meeting: the teacher knows what the student needs, but can't get it onto the IEP in a form that survives a records review. This prompt translates clinical intuition into compliant goal language.",
    setup: "Have the teacher describe the concern in plain English. Paste that, plus the student's grade, disability classification, and current performance data.",
    prompt: "You are a special education teacher-coach and certified IEP writer. Below is a teacher's narrative concern about a student, with grade level, classification, and current data. Produce three alternative annual goal options for this student. Each goal must contain: (a) the student's name placeholder [Student]; (b) the conditions under which the behavior will occur; (c) the observable target behavior; (d) the measurable criterion for mastery; (e) the timeframe; (f) how progress will be measured (tool, frequency, who collects the data). After the three goals, explain in one paragraph which of the three you'd recommend and why, based on the data provided. Then write two short-term objectives for the recommended goal. NARRATIVE: [paste]"
  },
  {
    id: 3,
    featured: true,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Annual CSE Packet Synthesis",
    description: "Upload every evaluation, progress report, and teacher input form. Produce a defensible meeting brief that honors 40 pages of documentation in 2.",
    why: "Annual review season means 80+ meetings in six weeks. The work that suffers is the synthesis — reading every document and threading it into a coherent narrative. That's also the work that parents notice when it's missing.",
    setup: "Create a NotebookLM for each student with all source documents: prior IEP, psychoed eval, related service reports, teacher input forms, progress monitoring data, parent input form if returned.",
    prompt: "You are preparing a CSE annual review brief. Using only the documents in this notebook, produce: (1) a two-paragraph narrative that describes this student as a learner — strengths first, then areas of need — citing the source document for each claim; (2) a progress summary for every current goal, citing the data; (3) the three areas where the team is most likely to disagree at the meeting (level of service, classification, LRE) with what each document suggests; (4) parent concerns as documented in the parent input form or prior meeting minutes, with a recommended response for each; (5) a proposed agenda that hits every required element of §200.4(d)(3) in the time available; (6) any document that is missing, stale, or internally contradictory. Do not make up data that isn't in the sources."
  },
  {
    id: 4,
    tool: "claude",
    toolLabel: "Claude",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Declassification Analysis",
    description: "Decide whether a student is ready to exit special education — and write the recommendation in a form the parent can trust.",
    why: "Declassification is one of the hardest meetings in the job. The data often supports it, but the parent doesn't. A careful analysis — with the transition supports written out — is the difference between a clean exit and a due process filing.",
    setup: "Gather three years of progress data, current goals and mastery levels, general education teacher input, and parent input if available. Paste everything.",
    prompt: "You are a school psychologist and CSE chair. Using the data below, produce a declassification analysis. Cover: (1) the original reason for classification and whether those needs are still present; (2) the pattern of progress on goals over the last three years, with specific data points; (3) whether the student is currently making effective progress in general education without specialized instruction, using objective measures; (4) the specific declassification supports that would follow (typically one year of continued accommodations / monitoring per §200.4(d)(1)); (5) the three concerns the parent is most likely to raise, with the team's response to each, grounded in the data; (6) a one-paragraph draft of the recommendation to the parent, warm but clear, explaining what declassification means and what continues. DATA: [paste]"
  },
  {
    id: 5,
    tool: "claude",
    toolLabel: "Claude",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Parent Response Letter — Disagreement",
    description: "The parent has filed a letter of disagreement after a CSE meeting. Draft a response that is legally accurate, warm, and opens the door.",
    why: "A letter of disagreement is the moment where a case either de-escalates or moves toward impartial hearing. The tone, the specificity, and the named next step matter more than any clinical argument.",
    setup: "Paste the parent's letter, the meeting minutes, the current IEP, and any specific points of contention. Note the student's classification and program.",
    prompt: "You are a pupil services director drafting a response to a parent letter of disagreement. Tone: warm, specific, legally careful, never defensive. Produce: (1) an opening paragraph that acknowledges what the parent said — specifically, not generically; (2) a point-by-point response to each concern raised, referencing the data or regulation that informed the team's recommendation; (3) the concrete next steps the district is offering — mediation, a reconvened CSE, an IEE at district expense, or a specific program trial — with a date or timeframe for each; (4) a plain-language statement of the parent's procedural safeguards (right to mediation, due process, etc.) without sounding like a threat; (5) a closing paragraph that names the shared goal — the student's progress. Draft in standard business letter format. PARENT LETTER: [paste] MEETING MINUTES: [paste] IEP: [paste]"
  },
  {
    id: 6,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "cse",
    domainLabel: "CSE / CPSE Chair",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "CSE Meeting Prep Brief — 15 Minutes Before",
    description: "The meeting is in fifteen minutes. Paste the case file. Walk in prepared.",
    why: "Every CSE chair knows the feeling — the meeting is starting and you haven't re-read the psychoed. A fast, structured brief on your phone is the difference between driving the meeting and being driven by it.",
    setup: "Paste the most recent evaluation summary, the current IEP, teacher input forms, and any recent email thread with the parent. Tell it what decision the meeting needs to make.",
    prompt: "You are my chief of staff. I am the CSE chair. The meeting starts in fifteen minutes. Using the documents below, give me exactly this, in this order, no preamble: (1) the student in one sentence — who they are as a learner; (2) the one decision this meeting needs to make; (3) the three numbers I need to have ready (progress on a key goal, current service minutes, assessment score); (4) the parent's most likely opening concern, and my one-sentence response; (5) the one thing I am most likely to forget. Keep it under 250 words. DOCUMENTS: [paste]"
  },

  // ───────── 504 & ADA ─────────
  {
    id: 7,
    tool: "claude",
    toolLabel: "Claude",
    domain: "plan504",
    domainLabel: "504 & ADA",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "504 Plan Draft from Medical Documentation",
    description: "Translate a physician's letter into a defensible 504 plan — major life activity, substantial limitation, reasonable accommodations.",
    why: "Most 504 plans fail not in the accommodations list but in the threshold finding — did the team actually analyze whether the impairment substantially limits a major life activity? A clean analysis protects the plan when it's challenged.",
    setup: "Paste the physician's letter and any other medical documentation. Note the student's grade and current school performance.",
    prompt: "You are a 504 coordinator and Section 504 compliance specialist. Based on the medical documentation below, draft the 504 plan framework. Cover: (1) the impairment as documented, not as assumed; (2) the major life activity affected, with specific citation to the ADAAA list or a documented life activity; (3) the analysis of whether the limitation is substantial, compared to most people in the general population (not compared to other accommodated students); (4) proposed accommodations — only those reasonably necessary for equal access, not those that would give advantage; (5) explicit distinction from IEP-level specialized instruction; (6) review date and re-evaluation trigger. Flag any accommodation the physician requested that is not supported by the documentation, and explain why. DOCUMENTATION: [paste]"
  },
  {
    id: 8,
    tool: "claude",
    toolLabel: "Claude",
    domain: "plan504",
    domainLabel: "504 & ADA",
    sizes: ["md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "504 to IEP Transition Analysis",
    description: "A student on a 504 plan is struggling. Is it time to refer for a CSE evaluation? This analysis makes the case either way.",
    why: "This decision is made constantly and poorly. Teams either keep stacking accommodations on a 504 past the point of helpfulness, or refer to CSE without the data to support eligibility. A clean analysis protects the student and the team.",
    setup: "Paste current 504 plan, response-to-accommodation data, teacher narratives, recent assessment data, and parent input.",
    prompt: "You are a school psychologist advising a student support team. Using the data below, answer: is this student appropriately served by a 504 plan, or should the team consider a referral to CSE for evaluation under IDEA? Produce: (1) the pattern the data shows — is the student making meaningful progress with current accommodations, or not; (2) whether the concerns suggest a suspected disability under IDEA that would require specialized instruction, not just accommodations; (3) the specific IDEA classifications the profile most closely matches, and the data points that support each; (4) the case against referral, honestly presented; (5) a recommended next step — continue 504 with modifications, referral to CSE, or a time-limited tier 3 intervention with progress monitoring first. DATA: [paste]"
  },
  {
    id: 9,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "plan504",
    domainLabel: "504 & ADA",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Accommodation Implementation Audit",
    description: "Are the accommodations on the plan actually being delivered in the classroom? Audit a teacher's implementation without making it adversarial.",
    why: "Most 504 and IEP complaints come down to implementation — the accommodation is in the plan but not happening on Wednesday afternoon in seventh-period math. The audit lets you find out without running an investigation.",
    setup: "Paste the accommodation list, the student's schedule, and recent work samples or teacher-reported concerns.",
    prompt: "You are a special education administrator designing a non-adversarial implementation audit. For the accommodation list below, produce: (1) for each accommodation, a one-question check-in for the teacher that is specific enough to reveal whether it is being implemented, but not so pointed that it feels like a trap; (2) for each accommodation, a parallel question for the student that can be asked privately; (3) a work-sample evidence trail — what should appear in the student's work if the accommodation is being delivered; (4) a script for the follow-up conversation with a teacher whose answers suggest the accommodation isn't happening, framed as support not compliance; (5) a summary memo template for the 504/CSE chair. ACCOMMODATIONS: [paste]"
  },

  // ───────── COMPLIANCE & STATE REPORTING ─────────
  {
    id: 10,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "compliance",
    domainLabel: "Compliance & Reporting",
    sizes: ["md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "IDEA Indicator Self-Audit",
    description: "Before the state does it — run your district's data against the IDEA State Performance Plan indicators and find the red flags.",
    why: "The indicators most districts get cited on (disproportionality, LRE percentage, graduation rate for SWD, suspension rate) are findable in your own data a year before the state letter arrives. The audit is the early warning.",
    setup: "Create a NotebookLM with your most recent SIRS reports, classification data by race/ethnicity, LRE percentages by building, discipline data, and graduation/dropout data disaggregated for students with disabilities.",
    prompt: "You are a NYSED special education compliance auditor. Using only the data in this notebook, audit our district against the IDEA State Performance Plan indicators. For each indicator (1: graduation, 2: dropout, 3: assessment, 4: suspension, 5: LRE, 9: disproportionality by race in classification, 10: disproportionality in specific classifications, 11: initial eval timelines, 12: preschool transition, 13: secondary transition, 14: post-school outcomes), produce: (a) our most recent reported rate; (b) the state target; (c) whether we are meeting, approaching, or not meeting; (d) the building or subgroup driving any gap; (e) the one corrective action that would most move the number. Flag any indicator where our data looks inconsistent or incomplete — that's a data-quality finding."
  },
  {
    id: 11,
    tool: "claude",
    toolLabel: "Claude",
    domain: "compliance",
    domainLabel: "Compliance & Reporting",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Timeline Compliance Checker",
    description: "Initial eval timelines, annual review dates, triennial reevaluations — catch the overdue cases before the state report runs.",
    why: "Timeline violations are the single most common source of compliance findings, and they're preventable. A weekly audit is a 30-minute habit that protects you for the year.",
    setup: "Export the active student list with initial eval dates, most recent CSE/CPSE meeting dates, most recent reevaluation dates, and referral dates for students in process.",
    prompt: "You are a compliance auditor. From the student data below, produce: (1) every initial evaluation where the 60 school-day timeline from consent to CSE meeting has been exceeded or will be exceeded in the next 30 days; (2) every annual review where the anniversary date will pass in the next 30 days without a scheduled meeting; (3) every reevaluation where the three-year window will close in the next 60 days; (4) every preschool transition case (CPSE to CSE) where the child's third birthday is within 90 days and transition planning has not yet occurred; (5) a prioritized action list with the five cases most urgent to schedule this week. Present as a clean table. Do not include student names in any narrative — use case IDs only. DATA: [paste]"
  },
  {
    id: 12,
    featured: true,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "compliance",
    domainLabel: "Compliance & Reporting",
    sizes: ["md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "State Complaint / Due Process Prep",
    description: "A complaint has been filed. Build the chronology, document index, and narrative response — defensible, specific, and honest.",
    why: "State complaints and due process filings reward preparation. A careful chronology, a complete document index, and a narrative that actually engages the parent's claim — rather than boilerplate denial — is the difference between an early resolution and a hearing.",
    setup: "Upload the complaint or due process notice, every IEP and meeting minute in the case history, every email between the district and the parent, every evaluation, every progress report.",
    prompt: "You are a special education attorney preparing the district's response. Using only the documents in this notebook, produce: (1) a chronology of every relevant event with date, participants, and document citation — from the first referral to the present; (2) a document index keyed to the chronology, numbered for production; (3) for each specific allegation in the complaint, the document(s) that support the district's position and the document(s) that support the parent's position — honestly; (4) the three strongest points in the district's position; (5) the two weakest points — things opposing counsel will name at hearing; (6) a draft narrative response that is factual, specific, and free of boilerplate; (7) a resolution-session offer that addresses the parent's stated concerns without conceding any legal position. Flag any document that appears to be missing from the record."
  },

  // ───────── MTSS / RTI ─────────
  {
    id: 13,
    tool: "claude",
    toolLabel: "Claude",
    domain: "mtss",
    domainLabel: "MTSS / RTI",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Tier 2 Intervention Matcher",
    description: "A student is flagged in universal screening. Match them to the right tier 2 intervention based on the specific skill deficit, not the general score.",
    why: "Most tier 2 matching happens by score band, which is why half the interventions don't move the needle. The right match is based on the specific sub-skill the student is failing, and the evidence base of the intervention for that sub-skill.",
    setup: "Paste the student's universal screener subtest scores, any diagnostic data, current reading or math level, and what interventions your building actually has available.",
    prompt: "You are an MTSS coordinator. Using the data below, recommend a tier 2 intervention match. Produce: (1) the specific skill deficit pattern in the data — not the composite score, but the sub-skills; (2) the three interventions on our available list with the strongest evidence base for that specific deficit, citing What Works Clearinghouse or similar if relevant; (3) the recommended intervention, dosage (minutes per session, sessions per week, duration in weeks), and progress monitoring measure; (4) the decision rule for moving to tier 3 or returning to tier 1; (5) what we should see in 6 weeks if the intervention is working. STUDENT DATA: [paste] AVAILABLE INTERVENTIONS: [paste]"
  },
  {
    id: 14,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "mtss",
    domainLabel: "MTSS / RTI",
    sizes: ["md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Universal Screener Pattern Analysis",
    description: "Upload three benchmark windows of screener data. Find the students the data is telling you to notice — even if their teachers haven't yet.",
    why: "The students who drop a half-grade between benchmarks are invisible on a single report. Across three windows, the pattern is obvious. Finding them early is the difference between tier 2 and a formal referral.",
    setup: "Upload fall, winter, and spring benchmark files for the current year. Include grade, classroom teacher, and screener subscores.",
    prompt: "You are a reading specialist analyzing screener data across three benchmark windows. Produce: (1) every student who dropped at least one performance band from fall to winter — names, grades, subtest pattern; (2) every student who was flagged at tier 3 in fall and has not moved by spring; (3) classrooms where more than 30% of students are below benchmark — those are tier 1 issues, not tier 2; (4) the subtest where our district-wide performance dropped the most; (5) the five students whose data pattern most suggests a previously unidentified disability. Present each section as a clean table with student ID (no names). Do not speculate beyond what the data supports."
  },
  {
    id: 15,
    tool: "claude",
    toolLabel: "Claude",
    domain: "mtss",
    domainLabel: "MTSS / RTI",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "MTSS Fidelity Check",
    description: "Your district has an MTSS framework on paper. Is it being implemented in practice? A building-by-building audit.",
    why: "MTSS fails quietly — the framework is adopted, the posters go up, but the data meetings don't happen and tier 2 becomes 'whatever the teacher does.' A fidelity check reveals it before the state auditor does.",
    setup: "Paste your MTSS framework document, data meeting schedules from each building, recent intervention logs, and progress monitoring data.",
    prompt: "You are an MTSS coach evaluating implementation fidelity. Using the materials below, produce: (1) for each building, a rating on the four pillars of MTSS fidelity (universal screening, tiered interventions with evidence base, progress monitoring, data-based decision making) with specific evidence; (2) the building with the highest fidelity and what they are doing that could be replicated; (3) the building with the lowest fidelity and the specific practice that needs to start in the next 30 days; (4) the district-wide gap that no building is closing on its own; (5) a draft 90-day action plan for the lowest-fidelity building with three specific, observable changes. MATERIALS: [paste]"
  },
  {
    id: 16,
    tool: "claude",
    toolLabel: "Claude",
    domain: "mtss",
    domainLabel: "MTSS / RTI",
    sizes: ["md","lg","xl","xl"],
    locales: ["suburban","urban"],
    title: "Early Warning System Review",
    description: "Attendance, behavior, course performance — combine the three into an early warning list that names the twenty students who need a conversation this week.",
    why: "Early warning indicators work, but only when a human acts on them. A clean weekly list, with recommended first moves, is what makes the difference.",
    setup: "Export current attendance rate, discipline incidents year-to-date, and current course grades for grades 6-12. Flag any student with an active IEP or 504.",
    prompt: "You are a student services coordinator building a weekly early warning list. Using the data below, produce: (1) the top 20 students with the highest combined risk across attendance (below 90%), behavior (two or more incidents), and academics (one or more failing grades); (2) for each, the single indicator driving the flag, and whether it is escalating or stable; (3) which students on the list have an IEP or 504 — those cases may indicate a plan that isn't working, not just a student in trouble; (4) the three students most likely to be lost to the school in the next 30 days without an intervention; (5) a recommended first move for each of those three — the specific adult who should reach out, and what they should say. DATA: [paste]"
  },

  // ───────── RELATED SERVICES ─────────
  {
    id: 17,
    tool: "claude",
    toolLabel: "Claude",
    domain: "related",
    domainLabel: "Related Services",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Individualized Health Plan Review",
    description: "The nurse drafts the IHP, you approve it. A structured review catches the gaps between health needs, 504 plans, and IEPs.",
    why: "Health plans, 504 plans, and IEPs are often drafted by different people and never cross-referenced. A child with diabetes, an IEP for a learning disability, and a 504 for testing accommodations can have three plans that disagree on emergency protocols.",
    setup: "Paste the draft IHP, the student's 504 plan and/or IEP if applicable, and the physician's orders.",
    prompt: "You are a district medical director reviewing an IHP draft. Produce: (1) is the IHP consistent with the physician's orders — flag any discrepancy; (2) are the emergency protocols specific enough for a substitute nurse to execute without calling — if not, what is missing; (3) does the IHP conflict with any accommodation in the 504 or IEP (testing location, field trip participation, PE participation) — name each conflict; (4) does the plan address transportation, field trips, after-school activities, and unscheduled substitutes, or only the school day; (5) the parent communication protocol — is it specific about who calls whom and when; (6) one recommended revision that would most improve the plan. IHP: [paste] 504/IEP: [paste] PHYSICIAN ORDERS: [paste]"
  },
  {
    id: 18,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "related",
    domainLabel: "Related Services",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Counseling Caseload Triage",
    description: "The school counselor has 300 students and 40 on the caseload. Who actually needs to be seen this week, and who can wait?",
    why: "Counseling and social work caseloads grow by accretion. A structured triage reveals which students are on the list from two years ago and stable, versus which three added this month are acute.",
    setup: "Paste the current caseload with date added, presenting concern, last contact date, risk level if rated, and any IEP counseling service minutes.",
    prompt: "You are a school counseling supervisor triaging a caseload. Using the data below, produce: (1) the five students who most clearly need contact this week based on the data — recency of concern, escalation, or mandated IEP service; (2) the five students who have been on the caseload longest without a change in status — candidates for discharge or a different level of support; (3) IEP-mandated counseling where the service log shows the minutes aren't being delivered — this is a compliance issue; (4) a recommended weekly structure for the counselor that honors IEP mandates first, tier 3 crisis second, and tier 2 supportive contact third; (5) the two cases that should be staffed with the district psychologist this month. CASELOAD: [paste]"
  },
  {
    id: 19,
    tool: "claude",
    toolLabel: "Claude",
    domain: "related",
    domainLabel: "Related Services",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "FBA / BIP Drafting Assistant",
    description: "Turn a functional behavior assessment into a behavior intervention plan that teachers can actually implement on Monday.",
    why: "Most BIPs fail not in the analysis but in the implementation — the replacement behavior is vague, the antecedent strategies are generic, and the data collection system takes more time than the teacher has.",
    setup: "Paste the FBA summary including antecedent patterns, consequence patterns, and the hypothesized function of the behavior. Note the setting and the teacher's realistic capacity.",
    prompt: "You are a BCBA translating an FBA into an implementable BIP. Using the FBA below, produce: (1) a one-sentence hypothesis of function in plain English; (2) three antecedent strategies the classroom teacher can implement without additional materials or training; (3) the specific replacement behavior the student will be taught, with the teaching procedure; (4) the reinforcement schedule for the replacement behavior — fixed, with a fade plan; (5) the response plan for the problem behavior, including the clear line that triggers a call to administration; (6) a data collection system that takes the teacher no more than 60 seconds per occurrence; (7) a fidelity check question for a weekly coaching visit. FBA: [paste]"
  },
  {
    id: 20,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "related",
    domainLabel: "Related Services",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Crisis Team Debrief Facilitator",
    description: "After a threat assessment, a hospitalization, or a self-harm incident — a structured debrief that protects the team and the next student.",
    why: "Crisis teams either don't debrief or debrief in a way that becomes a blame session. A facilitated structure honors the humans who did the work and surfaces the one thing to change for next time.",
    setup: "Describe the incident in general terms. Note who was on the team, the decisions made, and the timeline.",
    prompt: "You are a critical-incident debrief facilitator. Based on the summary below, produce: (1) an opening norm statement that centers the team's care for the student; (2) five questions in order — what we knew at the start, what we decided and why, what went well, what was harder than expected, what we would do differently next time — each with a suggested time allocation; (3) a protective reminder that this debrief is not an evaluation of any team member's performance; (4) a closing prompt that asks each member to name one resource or support they need in the next week; (5) a follow-up action template for the administrator. Keep the whole thing to 45 minutes. INCIDENT: [paste]"
  },

  // ───────── McKINNEY-VENTO & EQUITY ─────────
  {
    id: 21,
    tool: "claude",
    toolLabel: "Claude",
    domain: "equity",
    domainLabel: "McKinney-Vento & Equity",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "McKinney-Vento Identification Letter",
    description: "A family's registration form raises a flag — couch-surfing, recent eviction, living in a motel. Draft the outreach that identifies without stigmatizing.",
    why: "McKinney-Vento works only if the family self-identifies, and self-identification only happens when the outreach feels like a resource, not an interrogation.",
    setup: "Paste the registration form information that raised the question. Do not use the family's name in your input.",
    prompt: "You are a McKinney-Vento liaison drafting a warm, resource-oriented letter to a family whose registration suggests they may qualify. Produce: (1) an opening paragraph that does not use the word 'homeless' and does not imply the family is in trouble; (2) a plain-language description of what McKinney-Vento provides — transportation to the school of origin, free meals, school supplies, fee waivers, tutoring access — as rights, not charity; (3) the specific question the family needs to answer, framed gently, with the option to decline; (4) the contact — name, phone, email, and whether they can come to the school or meet elsewhere; (5) a closing that reinforces that their child's education is secure regardless of how they answer. REGISTRATION INFO: [paste]"
  },
  {
    id: 22,
    tool: "claude",
    toolLabel: "Claude",
    domain: "equity",
    domainLabel: "McKinney-Vento & Equity",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Foster Care Transition Plan",
    description: "A student in foster care is moving placements. The 'best interest determination' and transportation plan that keeps them in the school of origin.",
    why: "ESSA's foster care provisions are newer and less familiar than McKinney-Vento, but the stakes are identical — the school of origin, when it's in the child's best interest, is the most stable thing in the child's life.",
    setup: "Note the student's current placement, the proposed new placement, the distance, any input from the caseworker, and the child's views if age-appropriate.",
    prompt: "You are the foster care point of contact under ESSA. Produce: (1) the factors for the best-interest determination — distance, length of anticipated placement, the child's age and views, any ties to the school of origin, disruption from a mid-year move — with the data for this case applied to each; (2) the recommended decision and rationale; (3) if the recommendation is to remain in the school of origin, a transportation plan naming the cost-sharing arrangement with the child welfare agency (Title I funds if applicable); (4) if the recommendation is to transfer, the immediate enrollment plan and the records transfer timeline; (5) the written notice to the foster parent / caseworker / biological parent as required, with appeal rights. CASE: [paste]"
  },
  {
    id: 23,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "equity",
    domainLabel: "McKinney-Vento & Equity",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Registration Equity Audit",
    description: "Are your registration procedures creating barriers that disproportionately affect poor, homeless, or immigrant families? An audit that names specifics.",
    why: "Districts get consent decrees for registration practices that looked reasonable from inside the building. Documents required, languages available, proof-of-residency protocols — these are where Office for Civil Rights complaints originate.",
    setup: "Upload the registration packet, the website enrollment page, all residency verification forms, the student handbook section on enrollment, and any translated materials.",
    prompt: "You are a civil rights compliance auditor. Using only the documents in this notebook, identify: (1) every document required for registration, and whether it creates a barrier for homeless, foster, immigrant, or rural-poor families — cite the specific requirement; (2) any residency verification protocol that would exclude a McKinney-Vento family, a doubled-up family, or a recently relocated family in violation of federal law; (3) the languages in which enrollment materials are available, and the languages spoken in our community but not served; (4) any fee mentioned in the packet that is not clearly marked as waivable; (5) any language in the packet that a reasonable family could read as a threat or a test of legal status; (6) five specific, concrete changes that would close the identified gaps, ranked by urgency."
  },

  // ───────── STAFF SUPERVISION & PD ─────────
  {
    id: 24,
    tool: "claude",
    toolLabel: "Claude",
    domain: "staff",
    domainLabel: "Staff & PD",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Special Education Teacher Evaluation Narrative",
    description: "The APPR rubric produces a score. The narrative makes it teach. Draft honest, specific feedback for a special education teacher.",
    why: "Special education teachers get evaluated on general-education rubrics that don't fit their work. A good narrative names what actually happens in a resource room or self-contained class, and gives the teacher something to grow on.",
    setup: "Paste observation notes, any student progress data the teacher is responsible for, the rubric scores, and the teacher's self-reflection.",
    prompt: "You are a pupil services director writing an evaluation narrative for a special education teacher. Tone: direct, specific, developmental, not boilerplate. Produce: (1) an opening paragraph that names what this teacher actually does well — specifically, with an example from the observation; (2) a data paragraph that cites the progress of the students on their caseload toward IEP goals; (3) the growth area — one priority, not five — with a specific instructional move to develop; (4) a commitment paragraph that names what the district will provide (coaching, PD, peer observation) to support growth; (5) a closing that reinforces the role of specialized instruction in the student's life. Avoid evaluation-speak. NOTES: [paste]"
  },
  {
    id: 25,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "staff",
    domainLabel: "Staff & PD",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Paraprofessional Assignment Optimizer",
    description: "You have 12 paraprofessionals, 40 students with mandates, and a schedule that was built around rooms not students. Rebuild it.",
    why: "Para assignments get built in August on last year's assumptions and are never revisited. A student's needs change, a para's skills aren't a fit, a team-teaching arrangement would cover two mandates at once — these are findable but not without a fresh look.",
    setup: "Paste the para roster with hours and certifications/skills, the student list with 1:1 or small-group mandates, the bell schedule, and current assignments.",
    prompt: "You are a pupil services director rebuilding a paraprofessional schedule. Using the data below, produce: (1) the three mandates that are not fully covered by the current assignment — name them; (2) the three paras whose skills are not a match for their current assignment — name the mismatch; (3) a proposed reassignment that covers every mandate, matches skills to needs, and creates at least one team-teaching block that serves multiple students; (4) the one mandate that cannot be covered with current staffing — name the hours short; (5) the justification narrative for any reassignment that will be hard conversations with the paras affected. DATA: [paste]"
  },
  {
    id: 26,
    tool: "claude",
    toolLabel: "Claude",
    domain: "staff",
    domainLabel: "Staff & PD",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Inclusion PD Plan",
    description: "A year-long PD plan for general education teachers on inclusive practice — grounded in the actual students in their classrooms, not generic strategies.",
    why: "Inclusion PD often fails because it's generic. The value is matching the content to the teachers' actual caseload — the four students with IEPs in Mrs. X's fourth period, not 'students with disabilities' as a category.",
    setup: "Paste a sample of the general education faculty's caseload — which teachers have which students with IEPs, the classification patterns, the goal patterns. Describe available PD time (faculty meetings, superintendent conference days, late-start Wednesdays).",
    prompt: "You are a PD coordinator designing a year-long inclusion series. Using the caseload patterns below, produce: (1) the three most common instructional needs across the faculty's combined caseload — these are your PD targets; (2) a calendar of 8 PD sessions matched to available time, each with a specific instructional move rather than a general topic; (3) a coaching structure that pairs general education teachers with special education colleagues for non-evaluative observation cycles; (4) the artifact each session produces — a lesson plan, a co-teaching script, a scaffolded text — that shows up in classrooms the next week; (5) a measure of impact that is not an attendance sheet. CASELOAD: [paste]"
  },

  // ───────── BUDGET, GRANTS, FAMILY ─────────
  {
    id: 27,
    featured: true,
    tool: "claude",
    toolLabel: "Claude",
    domain: "budget",
    domainLabel: "Budget & Family",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Out-of-District Placement Cost-Benefit",
    description: "The CSE is considering an approved private placement. The tuition is $110,000. The board-facing analysis that makes the case either way, honestly.",
    why: "Out-of-district placement decisions are the most financially consequential decisions a pupil services director makes, and they are also the right decision for certain students. The analysis has to be clean on the clinical side and defensible on the fiscal side.",
    setup: "Paste the current IEP, the placements considered (including the in-district options attempted), the cost of each, and the transportation implications.",
    prompt: "You are a pupil services director preparing a cost-benefit analysis for the superintendent and board. Produce: (1) a clinical summary — what this student needs, and what the data shows about the in-district program's capacity to meet it; (2) the in-district options attempted and outcome, honestly — not to justify the placement but to document due diligence; (3) the recommended placement and why, specifically matched to the student's need; (4) the total cost — tuition, transportation, related services, aide if needed — and the comparison to an enhanced in-district program at the same cost; (5) the LRE justification that will appear on the IEP; (6) the precedent question the board will ask — if we do this for one student, what do we do for the next one with a similar profile — with a principled answer; (7) the one thing that would change the recommendation. DATA: [paste]"
  },
  {
    id: 28,
    tool: "claude",
    toolLabel: "Claude",
    domain: "budget",
    domainLabel: "Budget & Family",
    sizes: ["md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "IDEA Part B Grant Narrative",
    description: "The grant narrative that wins — specific, data-driven, and tied to measurable student outcomes, not budget line items.",
    why: "Most IDEA Part B narratives read like budget justifications. The ones that get prioritized in state competitive cycles read like a theory of change for students.",
    setup: "Paste last year's narrative, your current performance data on IDEA indicators, the specific set-aside or discretionary line you are applying for, and the outcomes you propose to achieve.",
    prompt: "You are a grant writer with a specialty in IDEA Part B. Produce a narrative with: (1) a one-paragraph needs statement grounded in our specific district data, not national statistics; (2) the proposed project in one sentence a non-specialist can understand; (3) the theory of change — what changes for students, and what has to happen first to make that change; (4) the activities and budget, written as what students will experience, not what staff will purchase; (5) the measurable outcomes — specific numbers, not 'improved outcomes'; (6) the evaluation plan; (7) the sustainability plan for when the grant ends. Cite relevant evidence base (What Works Clearinghouse, IES practice guides) where applicable. DATA: [paste]"
  },
  {
    id: 29,
    tool: "claude",
    toolLabel: "Claude",
    domain: "budget",
    domainLabel: "Budget & Family",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Parent Meeting Prep — Difficult Conversation",
    description: "A parent is coming in angry, and they have cause. Walk in prepared for the conversation, not the confrontation.",
    why: "The conversations that go badly are the ones where the administrator walks in defending and the parent walks in documenting. Preparation means being ready to listen specifically and name the district's errors specifically.",
    setup: "Describe the situation — what happened, what the parent has said in writing, what you know the district got wrong, what you think the parent is asking for.",
    prompt: "You are a coach preparing me for a difficult meeting with a parent. Produce: (1) the three things the parent is likely to say in the first ten minutes — listed as quotes, not paraphrases; (2) for each, the response that acknowledges what is true without conceding what isn't — in plain English, not district-speak; (3) the mistake the district actually made, and the words I should use to name it; (4) the three outcomes the parent might accept, ordered from most to least likely, and what the district can live with in each; (5) the one thing I should not say under any circumstance; (6) a closing question to ask the parent that shifts the meeting from grievance to plan. SITUATION: [paste]"
  },
  {
    id: 30,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "budget",
    domainLabel: "Budget & Family",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Pupil Services Dashboard for the Board",
    description: "The board asks about special education every year. A dashboard narrative that shows the whole picture — compliance, outcomes, equity, cost.",
    why: "Pupil services is the department boards understand least and fund most. A clean annual narrative, told in numbers the board can follow, is how the department earns its budget for next year.",
    setup: "Upload the last three years of classification rates, LRE percentages, graduation and dropout rates for students with disabilities, discipline data disaggregated, out-of-district placement counts and costs, and state indicator performance.",
    prompt: "You are preparing the annual board presentation for pupil services. Using only the data in this notebook, produce: (1) an opening slide narrative — one paragraph that tells the board the story of this department this year, in plain English; (2) the compliance picture — are we meeting the state indicators, with specific numbers and three-year trends; (3) the student outcome picture — graduation, dropout, suspension, and LRE trends for students with disabilities; (4) the equity picture — classification and discipline patterns by race/ethnicity, honestly, with the gap the data shows; (5) the cost picture — out-of-district placement count and total cost, with the three-year trend and what drives it; (6) the three asks of the board for next year, each tied to a specific data point above; (7) the one thing the board will push back on, and my response. Keep the whole thing to what fits on a ten-slide deck."
  }
];
